# Infrastructure pipeline

name: AWS infrastructure
trigger:
- main

variables:
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/ecr/ecr_exercise'
  terraformVersion: '1.4.6'

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
    - job: Install
      displayName: install_tf
      pool: taller-agent
      steps:
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: $(terraformVersion)
