# Infrastructure pipeline

name: AWS infrastructure
trigger:
- main

variables:
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/ecr/ecr_exercise'

stages:
  - stage: TerraformContinuousIntegration
    displayName: Terraform Module - CI
    jobs:
    - job: Install
      displayName: install_tf
      pool: taller-agent
      steps:
      - task: TerraformTaskV4@4
        displayName: Initialize Terraform
        inputs:
          provider: aws
          backendServiceAWS: 'aws_terraform'
          backendAWSBucketName: 'backend-tfstate-aws'
          backendAWSKey: test.tfstate
      - task: terraform fmt
        displayName: 'terraform fmt'
        inputs:
          provider: aws
          command: fmt        
      - task: terraform validate
        displayName: 'terraform validate'
        inputs:
          provider: aws
          command: validate
      - task: terraform plan
        displayName: 'terraform plan'
        inputs:
          provider: aws
          command: plan
          environmentServiceNameAWS: 'aws_terraform'
          